### ISSUE TITLE
Flares show up in front of the Sun when they shouldn't

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [MOARdV/DistantObject#26] opened 2016-02-20 00:58 UTC
I see Jool on the face of the Sun, when it's actually around the back side (ca. Year 1 Day 84).

**Comment by MOARdV** [comment] 2016-02-20 14:34
Yeah, I saw that a while back.  I don't know if I have any info about the size of the Sun so I can determine occlusion.

**Comment by drewcassidy** [comment] 2016-07-02 19:38
Im getting this issue with moho in version 1.7.2, ksp 1.1.3

<img width="1280" alt="screen shot 2016-07-02 at 12 38 03 pm" src="https://cloud.githubusercontent.com/assets/3837797/16542157/db7e446a-4051-11e6-8a98-3121512765c2.png">
<img width="1280" alt="screen shot 2016-07-02 at 12 37 58 pm" src="https://cloud.githubusercontent.com/assets/3837797/16542158/deda06d0-4051-11e6-89bf-890a76b780fb.png">

**Comment by MOARdV** [comment] 2016-07-02 19:49
@drewcassidy - one problem may be that the "sun" that is visible in space isn't the same size as the "sun" in the database.  Short of making a hack that ignores the size of the sun, I don't know what I can do about that.  Although it may be that I messed something up and the feature isn't working correctly.  I will look at it.

**Comment by MOARdV** [comment] 2016-11-12 00:09
Checked the "flare in front of the sun" issue again.  The problem is that the "sun" drawn in the skybox is much bigger than the radius provided in the Celestial Body (apparent size is 2x the radius of Kerbol, AFAICT).  I am not going to introduce a hack to change the behavior, since it'll be entirely dependent on a stock KSP installation - something that affects sun flares would introduce a change in behavior that will generate complaints, so I'm closing this as "as good as it gets".

**Closed by MOARdV** 2016-11-12 00:09 UTC
Labels: bug
