### ISSUE TITLE
Visual artifact in map view (white disc) when zooming out

### ISSUE THREAD

**Issue by Sethur** [MOARdV/DistantObject#9] opened 2015-04-01 21:50 UTC
As reported in the forum thread, I also experience a strange visual artifact with DOE 1.5.2 while zooming out. I'm using ATM Basic and -force-opengl under Windows running KSP 0.90 32bit.

The artifact looks like a white oval/disc quickly emerging from the vessel symbol, running towards the observer to disappear. The whole thing takes < 0.5s, but it's very annoying since it happens on every scroll wheel action.

The artifact looks like the image below:

![image](https://cloud.githubusercontent.com/assets/2142589/6953458/c439f8c6-d8c9-11e4-82a2-823e796efeec.png)

**Comment by Sethur** [comment] 2015-04-01 21:54
PS: The disc look suspiciously like DistantObject\Flare\model000.png, so I am quite sure this is caused by DOE 1.5.2. I will try downgrading to 1.5.1 now. Btw, I deactivated the rendering of flares in 1.5.2, but this did not solve the issue.

**Comment by MOARdV** [comment] 2015-05-02 15:14
I still can't reproduce this locally, but I'm going to try something in 1.5.5 to see if it goes away.

**Comment by MOARdV** [comment] 2015-05-02 18:00
I've pushed version 1.5.5 of DOE out.  If you can try it and see if the bug still persists, I would appreciate it.

**Comment by MOARdV** [comment] 2015-06-21 00:40
Closing, since I've received no indication the bug is still present.

**Closed by MOARdV** 2015-06-21 00:40 UTC
Labels: bug
